### ISSUE TITLE
fails due no dockerhub creds

### ISSUE THREAD

**Issue by ikke-t** [rcarrata/devsecops-demo#14]
Hi,

I tried to install the demo, but it seems it fails due that it tries to pull postgresql image from dockerhub. Nowadays dockerhub requires auth, so it fails as the demo doesn't add credentials.

This should be implemented into demo:

https://docs.openshift.com/container-platform/4.7/openshift_images/managing_images/using-image-pull-secrets.html#images-pulling-from-private-registries_using-image-pull-secrets

**Comment by rcarrata** [comment]
Hello @ikke-t, I've installed the demo in a fresh 4.7 install in AWS (opentlc) and it worked for me perfectly, but I agree with you that we need to use the image pull secrets. I'm thinking also to move the cicd infra images (gogs, postgres, nexus, etc) to the quay.io registry. It's suitable this idea?

**Comment by ikke-t** [comment]
Would be nice if the images came from quay.io, yes. For me it immediately complained about dockerhub access denied. Probably somehow cloud IPs have been exceeding the free limits.

**Comment by rcarrata** [comment]
@ikke-t I'll add the images into quay.io / registry.redhat.io to avoid the dockerhub limit failure. Also I'll use as well the Nexus Operator to deploy latest and greatest Nexus version.

Meanwhile you can avoid the dockerhub rate limiting using:
https://developers.redhat.com/blog/2021/02/18/how-to-work-around-dockers-new-download-rate-limit-on-red-hat-openshift#authenticate_to_your_docker_hub_account

**Comment by rcarrata** [comment]
Branch with WIP work: https://github.com/rcarrata/devsecops-demo/tree/use_quay

**Comment by rcarrata** [comment]
@ikke-t solved in the 43d0507 commit. Merged into main branch and working now. Thanks for raise this issue!
