### ISSUE TITLE
Pipeline petclinic-build-dev - task scan image error

### ISSUE THREAD

**Issue by piggyvenus** [rcarrata/devsecops-demo#21]
Since I have a free docker.io account, I am getting this error. Is it possible to avoid this?

PodPpetclinic-build-dev-cw8uq2-deploy-check-s7lww-pod-9ts67
NamespaceNScicd
5 minutes ago
Generated from kubelet on ip-10-0-184-15.us-west-1.compute.internal
5 times in the last 13 minutes
Failed to pull image "centos": rpc error: code = Unknown desc = Error reading manifest latest in docker.io/library/centos: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

**Comment by rcarrata** [comment]
100% agree @piggyvenus, the dockerhub rate limit pops up sometimes. I'll add this issue also into the tshoot and I'll switch all the images to quay.io / registry.redhat.io as well.

Meanwhile for avoiding this you can add your dockerhub creds into your OCP cluster:

https://developers.redhat.com/blog/2021/02/18/how-to-work-around-dockers-new-download-rate-limit-on-red-hat-openshift#authenticate_to_your_docker_hub_account

**Comment by rcarrata** [comment]
Solved as result to move the dockerhub images to the quay.io / redhat.registry.io. Thanks for raise this issue @piggyvenus!
