### ISSUE TITLE
OCP 4.11 install

### ISSUE THREAD

**Issue by plewyllie** [rcarrata/devsecops-demo#58]
The pipelines operator was not coming up in my OCP 4.11 install. I had to deinstall the operator, and install it from the OperatorHub. Then, relaunching the install.sh worked.

Did not have time to investigate really the cause, but I thought I'd share the issue.

**Comment by plewyllie** [comment]
fixed the issue, coming in PR.

**Comment by rcarrata** [comment]
@plewyllie thanks for raising the issue and for solving this in a PR! 👍
